#!/usr/bin/env python3
"""Render the one-shot MySQL initializer from the ordered migrations.

The generated file is deliberately a MySQL client script.  ``SOURCE`` keeps
the migration files as the single source of truth while the adjacent ledger
rows make later incremental migration runs checksum-safe.
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path


APP_ROOT = Path(__file__).resolve().parents[2]
MIGRATION_ROOT = APP_ROOT / "deploy" / "mysql"
OUTPUT_PATH = MIGRATION_ROOT / "init.sql"
DATABASE = "oohstory_library"


def migration_paths() -> list[Path]:
    paths = sorted(MIGRATION_ROOT.glob("[0-9][0-9][0-9]_*.sql"))
    if not paths:
        raise RuntimeError("no MySQL migrations found")
    versions = [path.name.split("_", 1)[0] for path in paths]
    if len(versions) != len(set(versions)):
        raise RuntimeError("duplicate MySQL migration version")
    return paths


def render() -> str:
    lines = [
        "-- GENERATED by scripts/electronic-library/render_mysql_init_sql.py.",
        "-- Do not edit this file by hand; edit migrations and regenerate it.",
        "-- MySQL 8.0+ only. Run from the repository root with the mysql client.",
        "-- This initializer is intentionally fresh-schema only and contains no",
        "-- credentials or production data.",
        "",
        "SET NAMES utf8mb4 COLLATE utf8mb4_0900_ai_ci;",
        "SET time_zone = '+00:00';",
        "",
        f"CREATE DATABASE IF NOT EXISTS `{DATABASE}`",
        "    CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;",
        f"ALTER DATABASE `{DATABASE}`",
        "    CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;",
        f"USE `{DATABASE}`;",
        "",
        "DELIMITER $$",
        "CREATE PROCEDURE oohstory_assert_empty_schema()",
        "BEGIN",
        "    IF EXISTS (",
        "        SELECT 1",
        "        FROM information_schema.tables",
        "        WHERE table_schema = DATABASE()",
        "        LIMIT 1",
        "    ) THEN",
        "        SIGNAL SQLSTATE '45000'",
        "            SET MESSAGE_TEXT =",
        "                'OOHStory init requires a fresh empty database';",
        "    END IF;",
        "END$$",
        "DELIMITER ;",
        "CALL oohstory_assert_empty_schema();",
        "DROP PROCEDURE oohstory_assert_empty_schema;",
        "",
    ]
    for path in migration_paths():
        version = path.name.split("_", 1)[0]
        checksum = hashlib.sha256(path.read_bytes()).hexdigest()
        description = path.stem.replace("'", "''")
        lines.extend(
            [
                f"SOURCE deploy/mysql/{path.name};",
                "INSERT INTO schema_migrations (version, checksum, description)",
                f"VALUES ('{version}', '{checksum}', '{description}');",
                "",
            ]
        )
    lines.extend(
        [
            "-- Roles have no login credentials. Runtime users are created by",
            "-- deploy/mysql/runtime-users.sql with server-generated passwords.",
            "CREATE ROLE IF NOT EXISTS",
            "    'oohstory_library_reader_role'@'%',",
            "    'oohstory_library_writer_role'@'%',",
            "    'oohstory_public_reader_role'@'%';",
            f"GRANT SELECT ON `{DATABASE}`.*",
            "    TO 'oohstory_library_reader_role'@'%';",
            "GRANT SELECT, INSERT, UPDATE, DELETE, CREATE TEMPORARY TABLES",
            f"    ON `{DATABASE}`.*",
            "    TO 'oohstory_library_writer_role'@'%';",
            f"GRANT SELECT ON `{DATABASE}`.*",
            "    TO 'oohstory_public_reader_role'@'%';",
            "GRANT INSERT, UPDATE",
            f"    ON `{DATABASE}`.book_public_metrics",
            "    TO 'oohstory_public_reader_role'@'%';",
            "GRANT SELECT, INSERT, UPDATE",
            f"    ON `{DATABASE}`.book_public_metric_visitors",
            "    TO 'oohstory_public_reader_role'@'%';",
            "GRANT SELECT, INSERT, UPDATE, DELETE",
            f"    ON `{DATABASE}`.reader_comments",
            "    TO 'oohstory_public_reader_role'@'%';",
            "GRANT SELECT, INSERT, UPDATE, DELETE",
            f"    ON `{DATABASE}`.reader_comment_reactions",
            "    TO 'oohstory_public_reader_role'@'%';",
            "",
            "SELECT COUNT(*) AS applied_migrations FROM schema_migrations;",
            "SELECT COUNT(*) AS created_tables",
            "FROM information_schema.tables",
            "WHERE table_schema = DATABASE();",
            "SELECT COUNT(*) AS created_triggers",
            "FROM information_schema.triggers",
            "WHERE trigger_schema = DATABASE();",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if deploy/mysql/init.sql is not current",
    )
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT_PATH.is_file():
            print(f"missing generated file: {OUTPUT_PATH}", file=sys.stderr)
            return 1
        if OUTPUT_PATH.read_text(encoding="utf-8") != expected:
            print(
                "deploy/mysql/init.sql is stale; regenerate with "
                "scripts/electronic-library/render_mysql_init_sql.py",
                file=sys.stderr,
            )
            return 1
        print("deploy/mysql/init.sql is current")
        return 0
    OUTPUT_PATH.write_text(expected, encoding="utf-8")
    print(f"wrote {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
