-- GENERATED by scripts/electronic-library/render_mysql_init_sql.py.
-- Do not edit this file by hand; edit migrations and regenerate it.
-- MySQL 8.0+ only. Run from the repository root with the mysql client.
-- This initializer is intentionally fresh-schema only and contains no
-- credentials or production data.

SET NAMES utf8mb4 COLLATE utf8mb4_0900_ai_ci;
SET time_zone = '+00:00';

CREATE DATABASE IF NOT EXISTS `oohstory_library`
    CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
ALTER DATABASE `oohstory_library`
    CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE `oohstory_library`;

CREATE TEMPORARY TABLE `_oohstory_fresh_schema_guard` (
    allowed TINYINT NOT NULL,
    CONSTRAINT `OOHStory init requires a fresh empty database`
        CHECK (allowed = 1)
);
INSERT INTO `_oohstory_fresh_schema_guard` (allowed)
SELECT IF(EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = DATABASE()
    LIMIT 1
), 0, 1);
DROP TEMPORARY TABLE `_oohstory_fresh_schema_guard`;

SOURCE deploy/mysql/001_library_schema.sql;
INSERT INTO schema_migrations (version, checksum, description)
VALUES ('001', '2f3cc5ca8235f107e13bebdbdf277fa5da8fb5e39347b650a049cc132c0ac125', '001_library_schema');

SOURCE deploy/mysql/002_catalog_query_indexes.sql;
INSERT INTO schema_migrations (version, checksum, description)
VALUES ('002', 'ea8137bfbfca68aa2d68fc33041f0e8e04f6863f833a55562fb4ccc5c41415ce', '002_catalog_query_indexes');

SOURCE deploy/mysql/003_books_auto_increment.sql;
INSERT INTO schema_migrations (version, checksum, description)
VALUES ('003', '2d41dc525940cc56293bd096a00e9c179530aff4376e06da6f1d74094ab9629b', '003_books_auto_increment');

SOURCE deploy/mysql/004_catalog_auxiliary_tables.sql;
INSERT INTO schema_migrations (version, checksum, description)
VALUES ('004', 'aa944f975164d537028adf300f9b54a231f9179a7c1af8787c7e7703e7534bd8', '004_catalog_auxiliary_tables');

SOURCE deploy/mysql/005_catalog_status_counts.sql;
INSERT INTO schema_migrations (version, checksum, description)
VALUES ('005', 'e80c5da9f24346c78922a62d995b23844a6deb42a540c32cba40dfd9e5243049', '005_catalog_status_counts');

SOURCE deploy/mysql/006_scale_foundation.sql;
INSERT INTO schema_migrations (version, checksum, description)
VALUES ('006', '60904aa1efe93726e37d7023742291f22f52c787158eb63ec7035faf7328e97f', '006_scale_foundation');

SOURCE deploy/mysql/007_incremental_catalog_counters.sql;
INSERT INTO schema_migrations (version, checksum, description)
VALUES ('007', 'cb4bb484c701a286044fb43c2cce3a7767a095f5b37c02bab9172f68e3687b1f', '007_incremental_catalog_counters');

SOURCE deploy/mysql/008_public_reader_indexes.sql;
INSERT INTO schema_migrations (version, checksum, description)
VALUES ('008', '389e130eca174a24f7940741053b7ed38d9a48c08cb6ca6800ab18c94515e7a9', '008_public_reader_indexes');

SOURCE deploy/mysql/009_public_filter_counters.sql;
INSERT INTO schema_migrations (version, checksum, description)
VALUES ('009', '8bd4f5276e2f75b697033d5cb3f3e1abcbf6d78d8df5ba11d699dbb5edc98026', '009_public_filter_counters');

SOURCE deploy/mysql/010_plot_index.sql;
INSERT INTO schema_migrations (version, checksum, description)
VALUES ('010', '56c3113534b8b5dd85a10e24d701dc74a96284eed944bf92d49ec690db9c9259', '010_plot_index');

SOURCE deploy/mysql/011_library_runtime_jobs.sql;
INSERT INTO schema_migrations (version, checksum, description)
VALUES ('011', 'edd5f2f3e26077d86f974693e80c76de66d64ad2ba96f8925b81ec12a837b1b1', '011_library_runtime_jobs');

SOURCE deploy/mysql/012_plot_index_constraints.sql;
INSERT INTO schema_migrations (version, checksum, description)
VALUES ('012', 'bde4a6124d28922545cdf027acad713d2dd4e8ed22a05930fb2d12245152e1d2', '012_plot_index_constraints');

SOURCE deploy/mysql/013_derived_index_checkpoints.sql;
INSERT INTO schema_migrations (version, checksum, description)
VALUES ('013', 'f8dcce6b90a49ccefff3cfa392187f6e1500b0a2bc4914a0ad9c96e8dda78117', '013_derived_index_checkpoints');

SOURCE deploy/mysql/014_serialized_source_updates.sql;
INSERT INTO schema_migrations (version, checksum, description)
VALUES ('014', '756223b27966cc59e7f1b20a02afa3a7a4663487f5ca213cc93edc681b99b182', '014_serialized_source_updates');

SOURCE deploy/mysql/015_book_public_metrics.sql;
INSERT INTO schema_migrations (version, checksum, description)
VALUES ('015', '6b376a490258a2b343cf314fcce7f494b266b7619d5d10a43fff91e5e37aa35c', '015_book_public_metrics');

SOURCE deploy/mysql/016_book_public_ids.sql;
INSERT INTO schema_migrations (version, checksum, description)
VALUES ('016', '5e65ed5bc3163300ccda2da1044ed6610e8c2b6e8a04b67c3ea2d696e420891b', '016_book_public_ids');

SOURCE deploy/mysql/017_global_book_identity_claims.sql;
INSERT INTO schema_migrations (version, checksum, description)
VALUES ('017', '008a0a9c9a29a61346f15fc83e2521303ccc660b92328f0fc2698d3b6890c951', '017_global_book_identity_claims');

SOURCE deploy/mysql/018_local_source_upgrades.sql;
INSERT INTO schema_migrations (version, checksum, description)
VALUES ('018', '8b0f4043326366822e614e590db827d59b41003841fe8ed355c35d90065ade59', '018_local_source_upgrades');

SOURCE deploy/mysql/019_ai_cover_fallback_policy.sql;
INSERT INTO schema_migrations (version, checksum, description)
VALUES ('019', '284e4daa85030371ea03c95276a84f0c429c789329cd74432d4ab556bd38576d', '019_ai_cover_fallback_policy');

SOURCE deploy/mysql/020_local_source_upgrade_utc.sql;
INSERT INTO schema_migrations (version, checksum, description)
VALUES ('020', '22a38d1e2cb851d00116a7b3a4395b8406cd493bd595a618ddfdcce0eba8c6b4', '020_local_source_upgrade_utc');

SOURCE deploy/mysql/021_local_missing_cover_lookup.sql;
INSERT INTO schema_migrations (version, checksum, description)
VALUES ('021', 'c0749c420651b81bdded468ec26a88ffc36fec68533cc4620d43b2ebc0c3b9f0', '021_local_missing_cover_lookup');

SOURCE deploy/mysql/022_book_publication_controls.sql;
INSERT INTO schema_migrations (version, checksum, description)
VALUES ('022', 'bbf8c42cf07b3cfef18628c69d7ecb278bdf5fb18535aaa1eb50a51f5c4cdb3a', '022_book_publication_controls');

-- Roles have no login credentials. Runtime users are created by
-- deploy/mysql/runtime-users.sql with server-generated passwords.
CREATE ROLE IF NOT EXISTS
    'oohstory_library_reader_role'@'%',
    'oohstory_public_reader_role'@'%',
    'oohstory_library_writer_role'@'%';
GRANT SELECT ON `oohstory_library`.*
    TO 'oohstory_library_reader_role'@'%';
GRANT SELECT ON `oohstory_library`.*
    TO 'oohstory_public_reader_role'@'%';
GRANT INSERT, UPDATE ON `oohstory_library`.book_public_metrics
    TO 'oohstory_public_reader_role'@'%';
GRANT SELECT, INSERT, UPDATE ON `oohstory_library`.book_public_metric_visitors
    TO 'oohstory_public_reader_role'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE TEMPORARY TABLES
    ON `oohstory_library`.*
    TO 'oohstory_library_writer_role'@'%';

SELECT COUNT(*) AS applied_migrations FROM schema_migrations;
SELECT COUNT(*) AS created_tables
FROM information_schema.tables
WHERE table_schema = DATABASE();
SELECT COUNT(*) AS created_triggers
FROM information_schema.triggers
WHERE trigger_schema = DATABASE();
